services:
  - type: web
    name: hytrade-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: hytrade-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    plan: free
    autoDeploy: true
